services:
  redis:
    image: "redis:7.0-alpine"
    restart: always

  nginx:
    image: "nginx:stable-alpine"
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./cfg/${FLASK_CONFIG}_nginx.conf:/etc/nginx/nginx.conf
      - ./well-known:/well-known
      - /etc/letsencrypt:/letsencrypt
    restart: always

  boggler:
    container_name: boggler-flask
    env_file:
      - cfg/boggler.env
    image: boggler-flask
    build: .
    restart: always
