services:
  nginx:
    image: "nginx:stable-alpine"
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./cfg/nginx.conf:/etc/nginx/nginx.conf
      - ./well-known:/well-known
      - /etc/letsencrypt:/letsencrypt
    restart: always

  boggler:
    container_name: boggler-flask
    image: boggler-flask
    build: .
    restart: always
