services:
  boggler:
    container_name: boggler-flask
    env_file:
      - cfg/docker.env
    image: boggler-flask
    build: .
    restart: always
    ports:
      - "5000:5000"
    volumes:
      - ./data:/data

